"""
Consolidated post-it data across all batches.
Each entry: (category, sub-theme, text, source-image, batch)
Used to regenerate the post-it grids, raw transcript, and counts in insights.html.
"""

POSTITS = [
    # ============================================================
    # 🚲 TRANSPORT & MOBILITY
    # ============================================================

    # ---- Air & inter-city ----
    ("transport", "Air & inter-city", "High-speed rail from Sydney", "IMG_4495", 2),
    ("transport", "Air & inter-city", "Housing for people travelling on high-speed rail", "IMG_4504", 2),
    ("transport", "Air & inter-city", "Permeability + connectivity to Broadmeadow HSR — constraints of existing infrastructure (Throsby/Styx Creek)", "IMG_4505", 2),
    ("transport", "Air & inter-city", "International Airport — direct Singapore", "IMG_4495", 2),
    ("transport", "Air & inter-city", "Increased international flight routes — example: Queenstown", "IMG_4488", 2),
    ("transport", "Air & inter-city", "Newcastle → Jindabyne flight path :)", "IMG_4493", 2),
    ("transport", "Air & inter-city", "More International Connections", "IMG_4494", 2),
    ("transport", "Air & inter-city", "Airport connections", "IMG_4492", 2),
    ("transport", "Air & inter-city", "More connectivity to travel + visit family. Also, increased flights to different cities", "IMG_4491", 2),
    ("transport", "Air & inter-city", "Electric vertical take-off aircraft", "IMG_4491", 2),
    ("transport", "Air & inter-city", "People — airport to CBD??", "IMG_4502", 2),
    ("transport", "Air & inter-city", "Ferry finishes too early ✓", "IMG_4466", 1),
    ("transport", "Air & inter-city", "More Planning for Airport transport — i.e. reliable buses", "IMG_4523", 3),
    ("transport", "Air & inter-city", "Real Bus to Airport", "IMG_4525", 3),
    ("transport", "Air & inter-city", "Get me to the airport", "IMG_4523", 3),
    ("transport", "Air & inter-city", "Airport Transport — park 7pm from Newcastle Interchange", "IMG_4542", 3),
    ("transport", "Air & inter-city", "I catch the uni train (Warabrook) to Newcastle Interchange for the airport bus", "IMG_4542", 3),
    ("transport", "Air & inter-city", "Why is there only one ferry line?", "IMG_4523", 3),

    # ---- Public transport (rail / tram / bus / ferry) ----
    ("transport", "Public transport", "Faster, safer, comfortable, accessible — public transport", "IMG_4523", 3),
    ("transport", "Public transport", "Faster and more frequent trains", "IMG_4501", 2),
    ("transport", "Public transport", "Reliability + frequency", "IMG_4507", 2),
    ("transport", "Public transport", "More connected public transport", "IMG_4506", 2),
    ("transport", "Public transport", "Better public transport across main routes — fast", "IMG_4495", 2),
    ("transport", "Public transport", "Better public transport between [precincts] — social opportunity", "IMG_4523", 3),
    ("transport", "Public transport", "Extend the tram route", "IMG_4495", 2),
    ("transport", "Public transport", "Light Rail Loop — Argyle West / Mary East / Merewether / Hamilton", "IMG_4494", 2),
    ("transport", "Public transport", "Light-rail loop servicing Newy East / Merewether / Hamilton / Newy West", "IMG_4523", 3),
    ("transport", "Public transport", "TRAM TO Broadmeadow", "IMG_4506", 2),
    ("transport", "Public transport", "Extended tram lines", "IMG_4481", 2),
    ("transport", "Public transport", "Rail loop", "IMG_4481", 2),
    ("transport", "Public transport", "Newcastle Tube (like London) — connect outside the city to inside the city", "IMG_4481", 2),
    ("transport", "Public transport", "Underground / subway", "IMG_4534", 3),
    ("transport", "Public transport", "Tunnel — city to: Broadmeadow / West Newcastle / Lake Mac / Maitland / Airport", "IMG_4523", 3),
    ("transport", "Public transport", "Tunnel to Stockton", "IMG_4523", 3),
    ("transport", "Public transport", "Mini buses for commuters / for stations (Lake Macquarie, outer suburbs)", "IMG_4491", 2),
    ("transport", "Public transport", "Improved school buses (to reduce cars on roads at peak times) or safe bike routes for kids", "IMG_4500", 2),
    ("transport", "Public transport", "Improved level crossings or bridges to remove traffic choke points", "IMG_4500", 2),
    ("transport", "Public transport", "Buses so people have more access to career choices", "IMG_4489", 2),
    ("transport", "Public transport", "Light rail be in use when people want to use it (e.g. at night)", "IMG_4494", 2),
    ("transport", "Public transport", "Light-rail that runs past 9pm", "IMG_4522", 3),
    ("transport", "Public transport", "Make the light rail FREE on Friday, Saturday &amp; Sunday nights — e.g. 6pm–6am", "IMG_4519", 3),
    ("transport", "Public transport", "FREE TRAM AT NIGHT", "IMG_4529", 3),
    ("transport", "Public transport", "FREE BUS + TRAM SUNDAYS", "IMG_4496", 2),
    ("transport", "Public transport", "FREE BUS in CBD", "IMG_4496", 2),
    ("transport", "Public transport", "FREE PUBLIC TRANSPORT in the city", "IMG_4494", 2),
    ("transport", "Public transport", "Make light-rail / public transport <em>free</em> — people getting out &amp; about", "IMG_4461", 1),
    ("transport", "Public transport", "Cheap / free transport @ night", "IMG_4538", 3),
    ("transport", "Public transport", "Maxi / Taxi / FREE BUSES", "IMG_4527", 3),
    ("transport", "Public transport", "Easy transport between precincts", "IMG_4480", 2),
    ("transport", "Public transport", "Boat cruisers + ferry stops", "IMG_4533", 3),
    ("transport", "Public transport", "Make use of the train network for travel — bring tourists", "IMG_4494", 2),
    ("transport", "Public transport", "Train stops surrounded by high-density living", "IMG_4493", 2),
    ("transport", "Public transport", "Park &amp; Ride @ Cameron Park — connecting to upper Newy", "IMG_4504", 2),
    ("transport", "Public transport", "Park &amp; Ride on city perimeter — connected to public transport + active transport", "IMG_4525", 3),
    ("transport", "Public transport", "Optimal lighting to suburbs", "IMG_4506", 2),
    ("transport", "Public transport", "Extend light rail to suburbs + include bike parking", "IMG_4495", 2),
    ("transport", "Public transport", "Transport after hours", "IMG_4485", 2),
    ("transport", "Public transport", "Rail East to West [reading uncertain]", "IMG_4512", 2),

    # ---- Cycling & e-bikes ----
    ("transport", "Cycling & e-bikes", "BIKES RULE THE ROAD", "IMG_4487", 2),
    ("transport", "Cycling & e-bikes", "I ride my bike from the Junction to the Harbour for exercise + social outings", "IMG_4487", 2),
    ("transport", "Cycling & e-bikes", "Bike lanes!", "IMG_4501", 2),
    ("transport", "Cycling & e-bikes", "More dedicated cycling lanes", "IMG_4495", 2),
    ("transport", "Cycling & e-bikes", "More cycling access", "IMG_4535", 3),
    ("transport", "Cycling & e-bikes", "More bike paths", "IMG_4492", 2),
    ("transport", "Cycling & e-bikes", "MORE LANES FOR E-BIKES", "IMG_4506", 2),
    ("transport", "Cycling & e-bikes", "Cycleways &amp; e-bike hire — like in Sydney", "IMG_4506", 2),
    ("transport", "Cycling & e-bikes", "E-Bike SAFETY LICENSE", "IMG_4497", 2),
    ("transport", "Cycling & e-bikes", "Pump tracks", "IMG_4492", 2),
    ("transport", "Cycling & e-bikes", "Active transport routes through green spaces, adjacent to rail corridors. Share bikes for tourists", "IMG_4500", 2),
    ("transport", "Cycling & e-bikes", "Better active transport — social + health + safety", "IMG_4522", 3),
    ("transport", "Cycling & e-bikes", "Little bikes, or other tap-on / tap-off bikes &amp; scooters", "IMG_4490", 2),
    ("transport", "Cycling & e-bikes", "Lighting on / at the bike path ↓", "IMG_4485", 2),
    ("transport", "Cycling & e-bikes", "Commuter path Fernleigh to Newy CBD 🍃", "IMG_4546", 3),
    ("transport", "Cycling & e-bikes", "Bike/Cycle — way improvements to make cyclists safe like they did in Sydney", "IMG_4460", 1),
    ("transport", "Cycling & e-bikes", "More opportunities / infrastructure to support bike riding &amp; walking (leave the cars at home)", "IMG_4459", 1),
    ("transport", "Cycling & e-bikes", "E-bike hire available throughout the city to create accessibility to all areas — for visitors", "IMG_4463", 1),
    ("transport", "Cycling & e-bikes", "Block Honeysuckle Drive for weekends", "IMG_4464", 1),
    ("transport", "Cycling & e-bikes", "Make Fernleigh track safer — walkers, females, people not on e-bikes (speed limit required)", "IMG_4469", 1),
    ("transport", "Cycling & e-bikes", "Share the road &amp; cycleway", "IMG_4464", 1),

    # ---- Cars / parking / EVs / autonomous ----
    ("transport", "Cars, parking & EVs", "Driverless cars? taxis?", "IMG_4496", 2),
    ("transport", "Cars, parking & EVs", "Driverless ubers or communal car-share", "IMG_4481", 2),
    ("transport", "Cars, parking & EVs", "Autonomous Pods…?", "IMG_4487", 2),
    ("transport", "Cars, parking & EVs", "Tata / Tesla cab [reading uncertain]", "IMG_4496", 2),
    ("transport", "Cars, parking & EVs", "Increase # of electric car charge stations", "IMG_4492", 2),
    ("transport", "Cars, parking & EVs", "EV charging in regional areas / towns", "IMG_4495", 2),
    ("transport", "Cars, parking & EVs", "Lack of city parking (impacting business)", "IMG_4495", 2),
    ("transport", "Cars, parking & EVs", "Secure parking in the city", "IMG_4495", 2),
    ("transport", "Cars, parking & EVs", "Parking hubs — showground?", "IMG_4493", 2),
    ("transport", "Cars, parking & EVs", "Congestion charge (like London)", "IMG_4490", 2),
    ("transport", "Cars, parking & EVs", "$$$ Triple rate for pensioners driving in CBD", "IMG_4496", 2),
    ("transport", "Cars, parking & EVs", "Close part of Honeysuckle Drive", "IMG_4496", 2),
    ("transport", "Cars, parking & EVs", "MAKE DARBY ST PEDESTRIAN ACCESS ONLY", "IMG_4494", 2),
    ("transport", "Cars, parking & EVs", "Go Get Car Share + bike / scooter share + carpool", "IMG_4525", 3),
    ("transport", "Cars, parking & EVs", "Car in / out of city from Central Coast", "IMG_4506", 2),
    ("transport", "Cars, parking & EVs", "Carpool karaoke — dating-app vibes for carpooling, matched by your Spotify playlist", "IMG_4487", 2),
    ("transport", "Cars, parking & EVs", "Dating-App vibes, but for carpool / transport share", "IMG_4487", 2),
    ("transport", "Cars, parking & EVs", "Web-based concept for public transport", "IMG_4535", 3),
    ("transport", "Cars, parking & EVs", "Transport on demand", "IMG_4546", 3),

    # ---- Tourism & experience travel ----
    ("transport", "Tourism & experience", "Casino Yacht", "IMG_4496", 2),
    ("transport", "Tourism & experience", "Gondola to the Church", "IMG_4496", 2),
    ("transport", "Tourism & experience", "Adventure Ship", "IMG_4497", 2),
    ("transport", "Tourism & experience", "Coal Tour Experience", "IMG_4497", 2),
    ("transport", "Tourism & experience", "FERRY: CARRINGTON / NEWCASTLE WEST to WHARF", "IMG_4497", 2),
    ("transport", "Tourism & experience", "Unisky String technologies (skyrail cycles)", "IMG_4495", 2),
    ("transport", "Tourism & experience", "Yes! More ways to actually move between places — with people + nature", "IMG_4491", 2),
    ("transport", "Tourism & experience", "Better connectivity", "IMG_4494", 2),

    # ---- Pain points & systemic asks ----
    ("transport", "Pain points & systemic", "Stop sweeping our social issues under the rug", "IMG_4497", 2),
    ("transport", "Pain points & systemic", "PAIN POINT — Buildings being built (Honeysuckle area) lack parking, so it's difficult to get to the businesses to enjoy the area", "IMG_4497", 2),
    ("transport", "Pain points & systemic", "PAIN POINT — I catch public transport because parking is difficult, but public transport is unsafe for a woman at night", "IMG_4497", 2),
    ("transport", "Pain points & systemic", "Increase quality of what we already have, rather than abandon what is already built", "IMG_4525", 3),
    ("transport", "Pain points & systemic", "Disconnect with Hunter Valley area and city area", "IMG_4543", 3),
    ("transport", "Pain points & systemic", "People who struggle to get out — due to distance, travel or caring responsibilities", "IMG_4544", 3),
    ("transport", "Pain points & systemic", "I live out of the city and drive to get into it", "IMG_4547", 3),
    ("transport", "Pain points & systemic", "Live in The Junction &amp; frequently walk up to Bar Beach &amp; areas; walk to and around The Junction village", "IMG_4543", 3),
    ("transport", "Pain points & systemic", "Under-represented: Cyclists", "IMG_4466", 1),
    ("transport", "Pain points & systemic", "Under-represented: Older demographic 65+ — hilly environment for non-drivers; lack of social activities tailored to older people", "IMG_4469", 1),
    ("transport", "Pain points & systemic", "Seniors card for transport, library, discounts; street-crossing extension", "IMG_4459", 1),

    # ============================================================
    # 🌿 HEALTH & WELLBEING
    # ============================================================

    # ---- Green & nature ----
    ("health", "Green & nature", "Yes! more green space ♥", "IMG_4535", 3),
    ("health", "Green & nature", "Purposefully creating meaningful green space", "IMG_4476", 2),
    ("health", "Green & nature", "Keep green spaces", "IMG_4484", 2),
    ("health", "Green & nature", "Green Spaces", "IMG_4480", 2),
    ("health", "Green & nature", "Green spaces near beaches", "IMG_4484", 2),
    ("health", "Green & nature", "Native plants spaces", "IMG_4486", 2),
    ("health", "Green & nature", "Street trees vibes", "IMG_4490", 2),
    ("health", "Green & nature", "More nature → when we're moving and staying in place", "IMG_4490", 2),
    ("health", "Green & nature", "Shaded spaces", "IMG_4484", 2),
    ("health", "Green & nature", "Animals (example being the new bypass)", "IMG_4476", 2),
    ("health", "Green & nature", "Community-led green-space projects", "IMG_4483", 2),
    ("health", "Green & nature", "Calm down — protect weekends", "IMG_4476", 2),
    ("health", "Green & nature", "Glenrock", "IMG_4476", 2),
    ("health", "Green & nature", "The beach", "IMG_4477", 2),
    ("health", "Green & nature", "Any beach", "IMG_4479", 2),
    ("health", "Green & nature", "&quot;Active&quot; Zones", "IMG_4479", 2),
    ("health", "Green & nature", "Reserved tree-planting spaces within green spaces", "IMG_4464", 1),
    ("health", "Green & nature", "Carbon-neutral green buildings (high number of buildings with plants incorporated)", "IMG_4466", 1),
    ("health", "Green & nature", "More tracks &amp; spaces to do stuff @ Glenrock ♥", "IMG_4467", 1),
    ("health", "Green & nature", "Protect — a healthier marine ecosystem", "IMG_4467", 1),

    # ---- Aged care & intergenerational ----
    ("health", "Aged care & intergenerational", "Childcare × aged care", "IMG_4476", 2),
    ("health", "Aged care & intergenerational", "Better aged care — alternatives to age well, celebrated &amp; valued", "IMG_4480", 2),
    ("health", "Aged care & intergenerational", "Redefine what aged care looks like", "IMG_4486", 2),
    ("health", "Aged care & intergenerational", "More intergenerational connectedness in meaningful ways", "IMG_4484", 2),
    ("health", "Aged care & intergenerational", "Better connection between youth + elderly", "IMG_4489", 2),
    ("health", "Aged care & intergenerational", "Multi-gen activities (e.g. aged care / TAFE to portal)", "IMG_4483", 2),
    ("health", "Aged care & intergenerational", "Integrate aged care with child care", "IMG_4461", 1),
    ("health", "Aged care & intergenerational", "More local community spaces in [each] neighbourhood for aged &amp; lonely people", "IMG_4462", 1),

    # ---- Loneliness, connection & community ----
    ("health", "Loneliness & connection", "Having meaningful personal relations", "IMG_4476", 2),
    ("health", "Loneliness & connection", "Conversational third spaces to encourage community engagement", "IMG_4477", 2),
    ("health", "Loneliness & connection", "Sense of &quot;community&quot; in your local neighbourhood — connecting with your neighbours", "IMG_4482", 2),
    ("health", "Loneliness & connection", "In Newy we say HI!", "IMG_4478", 2),
    ("health", "Loneliness & connection", "Feeling of &quot;not alone&quot; increases health → therefore community", "IMG_4478", 2),
    ("health", "Loneliness & connection", "Relationships, loneliness — opportunities with dignity", "IMG_4482", 2),
    ("health", "Loneliness & connection", "More ways to live # solo / isolation", "IMG_4479", 2),
    ("health", "Loneliness & connection", "Community 3rd spaces", "IMG_4489", 2),
    ("health", "Loneliness & connection", "PLACES &amp; SPACES where people can gather, organise themselves", "IMG_4489", 2),
    ("health", "Loneliness & connection", "Community Picnics", "IMG_4482", 2),
    ("health", "Loneliness & connection", "Communal pizza ovens — large wood-fired oven, bring along different dishes; the magic of community together is incredible", "IMG_4483", 2),
    ("health", "Loneliness & connection", "Community (city-wide) Program to involve everyone across multiple activities and ideas", "IMG_4483", 2),
    ("health", "Loneliness & connection", "More group events / activities (ideally free) that encourage people to use the facilities — e.g. free beach yoga, group hikes, meet-ups", "IMG_4483", 2),
    ("health", "Loneliness & connection", "More mood-mix communal areas — pre-school / library / aged care — stop loneliness", "IMG_4459", 1),
    ("health", "Loneliness & connection", "Public initiative to say &quot;hi!&quot; to strangers in nearby travels", "IMG_4463", 1),
    ("health", "Loneliness & connection", "School of life campus", "IMG_4482", 2),

    # ---- Equity, accessibility & inclusion ----
    ("health", "Equity & inclusion", "More inclusive — different abilities, ages / stages, races, religions", "IMG_4478", 2),
    ("health", "Equity & inclusion", "The facilities for disabled people", "IMG_4480", 2),
    ("health", "Equity & inclusion", "Disadvantaged", "IMG_4477", 2),
    ("health", "Equity & inclusion", "Disadvantaged youth are missing out", "IMG_4478", 2),
    ("health", "Equity & inclusion", "Young People", "IMG_4477", 2),
    ("health", "Equity & inclusion", "Greater visibility of First Nations culture", "IMG_4479", 2),
    ("health", "Equity & inclusion", "Visible Aboriginal lore of the location ✓", "IMG_4462", 1),
    ("health", "Equity & inclusion", "Migrant and refugees community spaces (e.g. free yoga + group)", "IMG_4483", 2),
    ("health", "Equity & inclusion", "Community Services", "IMG_4477", 2),
    ("health", "Equity & inclusion", "Programs + places for men + boys — to create community + mental health", "IMG_4485", 2),
    ("health", "Equity & inclusion", "Programs effective at addressing inequality + health", "IMG_4485", 2),
    ("health", "Equity & inclusion", "By 2050, ZERO harassment of women &amp; children", "IMG_4461", 1),
    ("health", "Equity & inclusion", "Safety in spaces (I want to run at night)", "IMG_4466", 1),
    ("health", "Equity & inclusion", "Community gardens — more involvement with diverse cultures", "IMG_4459", 1),

    # ---- Active recreation & programs ----
    ("health", "Active recreation", "MORE DOG PARKS", "IMG_4488", 2),
    ("health", "Active recreation", "Newy health festival? — tour to active sites; gyms / health centres get to advertise", "IMG_4484", 2),
    ("health", "Active recreation", "Map that shows the health / sport options. Groups like Newy Active Co. that encourage active living", "IMG_4488", 2),
    ("health", "Active recreation", "Walkable town centres — places to stop in the shade", "IMG_4478", 2),
    ("health", "Active recreation", "Safe walking for daily tasks — interesting + comfortable + walking → ↑ health", "IMG_4485", 2),
    ("health", "Active recreation", "Brisbane Southbank — free large communal water park", "IMG_4482", 2),
    ("health", "Active recreation", "OPEN FREE PUBLIC SPACE", "IMG_4488", 2),
    ("health", "Active recreation", "More EVENTS →", "IMG_4486", 2),
    ("health", "Active recreation", "Outdoor / nature activities / experiences", "IMG_4545", 3),
    ("health", "Active recreation", "Healing peoples' souls — experiencing community through nature", "IMG_4536", 3),
    ("health", "Active recreation", "Playgrounds (inner city) / Parks (inner city)", "IMG_4467", 1),
    ("health", "Active recreation", "Bogey Hole / Bar Beach / Hobbys [favourite swim spots]", "IMG_4469", 1),
    ("health", "Active recreation", "Bottom of Nobby's lighthouse beach", "IMG_4460", 1),
    ("health", "Active recreation", "Ocean baths → connection", "IMG_4467", 1),
    ("health", "Active recreation", "BMX 🚵 [with hill sketch]", "IMG_4468", 1),
    ("health", "Active recreation", "More wall ball / ball courts", "IMG_4464", 1),
    ("health", "Active recreation", "Subsidised rooms for gyms", "IMG_4461", 1),
    ("health", "Active recreation", "NDIS-subsidised gyms", "IMG_4465", 1),
    ("health", "Active recreation", "Free fitness classes (e.g. yoga, dance)", "IMG_4465", 1),
    ("health", "Active recreation", "Floating saunas in the harbour (between tugs?)", "IMG_4461", 1),
    ("health", "Active recreation", "5-min happiness factory — WALK HOME", "IMG_4465", 1),
    ("health", "Active recreation", "Art therapy sessions", "IMG_4459", 1),
    ("health", "Active recreation", "Support for other watersports outside surfing &amp; nippers", "IMG_4462", 1),

    # ---- Built environment & housing ----
    ("health", "Buildings & housing", "No mould in our homes, places of work, ALL BUILDINGS! → ↑ health", "IMG_4486", 2),
    ("health", "Buildings & housing", "Liveable housing means households are not financially stressed = ↑ wellbeing", "IMG_4482", 2),
    ("health", "Buildings & housing", "More well-lit areas to create safety when outside", "IMG_4490", 2),

    # ---- Health system & policy ----
    ("health", "Health system & policy", "Healthcare: NSW Health currently provides 80 contractual professional development tracks for in-work doctors but they pay for it. Factors-of-life, health risks, lifetime education, importance of social activities + education, all matter", "IMG_4491", 2),
    ("health", "Health system & policy", "Health is treated as such a side issue. Often the headlines aren't relevant to the patients — we want to make health feel less like a corporate", "IMG_4490", 2),
    ("health", "Health system & policy", "Ambassadors / holistic connectors — informed, empowered with creativity, that step back and look at the wider picture. Micro-health influencers", "IMG_4489", 2),
    ("health", "Health system & policy", "There's research, there's a trial, there's support — connecting the dots in health contexts", "IMG_4489", 2),
    ("health", "Health system & policy", "In Western Australia, all gambling [revenue redirected] to the community via Lottery West", "IMG_4484", 2),
    ("health", "Health system & policy", "Not having to work so hard for so many hours to afford basic amenities or healthy food", "IMG_4477", 2),
    ("health", "Health system & policy", "Share resources — do we need 50 washing machines in 50 [gyms]?", "IMG_4479", 2),
    ("health", "Health system & policy", "Queenstown [comparator place]", "IMG_4482", 2),

    # ============================================================
    # 🪩 NIGHT CULTURE & ECONOMY
    # ============================================================

    # ---- Activation & built form ----
    ("night", "Activation & built form", "The Wharf needs to change ✱", "IMG_4530", 3),
    ("night", "Activation & built form", "To re-vamp Hunter Street Mall — needs to be really popular and… [continued]", "IMG_4529", 3),
    ("night", "Activation & built form", "Hunter Street Mall has potential to have a number of bars grouped together + vibrant installations to make it safer", "IMG_4522", 3),
    ("night", "Activation & built form", "EAST END Development — age group 65–85", "IMG_4529", 3),
    ("night", "Activation & built form", "The Station Development — Brewery + Restaurants into Stadium, create activity", "IMG_4529", 3),
    ("night", "Activation & built form", "Good recent activation — @ Gallery, Tower Cinemas", "IMG_4529", 3),
    ("night", "Activation & built form", "Disused Devonshire St — Coast Potential for lighting / public art (especially when new business opens up)", "IMG_4521", 3),
    ("night", "Activation & built form", "New Newcastle Entertainment Centre — venue for large indoor concerts", "IMG_4519", 3),
    ("night", "Activation & built form", "New venue at Foreshore Stockton — on the ferry pier; tying it with the new Queen's Wharf facility", "IMG_4519", 3),
    ("night", "Activation & built form", "Better community use of previously communal areas — e.g. Newcastle train station — such a wasted opportunity", "IMG_4460", 1),
    ("night", "Activation & built form", "Closing a specific street to turn into an active space", "IMG_4463", 1),

    # ---- Live music, performance & arts ----
    ("night", "Live music & arts", "Live Music", "IMG_4536", 3),
    ("night", "Live music & arts", "More Live Music Events", "IMG_4536", 3),
    ("night", "Live music & arts", "Festivals, good bands, not alcohol", "IMG_4536", 3),
    ("night", "Live music & arts", "Outdoor live music — sunset, beachfront", "IMG_4537", 3),
    ("night", "Live music & arts", "Theatre + Arts", "IMG_4537", 3),
    ("night", "Live music & arts", "Theatre — more accessible outdoor performance", "IMG_4527", 3),
    ("night", "Live music & arts", "More events at venues like the Art Gallery or Museum", "IMG_4531", 3),
    ("night", "Live music & arts", "Night-time events at the Art Gallery or Museum", "IMG_4526", 3),
    ("night", "Live music & arts", "More ticks of approval from council for venues to do music nights", "IMG_4539", 3),
    ("night", "Live music & arts", "Why doesn't the Newcastle Uni buildings in town have more live music events at their venues?", "IMG_4520", 3),
    ("night", "Live music & arts", "Find more venues for live music — not many opportunities for young people / new bands to play", "IMG_4519", 3),
    ("night", "Live music & arts", "Street markets w/ music", "IMG_4546", 3),
    ("night", "Live music & arts", "Active / adventure — Art / music — healing peoples' souls — experiencing community through nature", "IMG_4536", 3),
    ("night", "Live music & arts", "Mega-tree outdoor programming + Plottes Theatre", "IMG_4462", 1),

    # ---- Outdoor, waterfront & nature at night ----
    ("night", "Outdoor & waterfront", "Late night swims at the baths", "IMG_4527", 3),
    ("night", "Outdoor & waterfront", "Late night swims", "IMG_4536", 3),
    ("night", "Outdoor & waterfront", "Bars, parks, night swimming", "IMG_4538", 3),
    ("night", "Outdoor & waterfront", "BBQ in laneway", "IMG_4527", 3),
    ("night", "Outdoor & waterfront", "BYO at views — drinks on harbour — live music…?", "IMG_4538", 3),
    ("night", "Outdoor & waterfront", "Outdoor cinema, but not for kids (because there's already a lot) — so more for adults, with wine and luxe bean bags", "IMG_4537", 3),
    ("night", "Outdoor & waterfront", "Open-air viewing of sports games :)", "IMG_4520", 3),
    ("night", "Outdoor & waterfront", "Beach front wine bar (can use picnic rug)", "IMG_4541", 3),
    ("night", "Outdoor & waterfront", "More picnic tables overlooking coast", "IMG_4541", 3),
    ("night", "Outdoor & waterfront", "Should be more opportunities to have bars / cafes etc along the beaches / coastline", "IMG_4520", 3),
    ("night", "Outdoor & waterfront", "Let cruise ships dock &amp; not leave till midnight", "IMG_4527", 3),
    ("night", "Outdoor & waterfront", "Cleanrock / King Edward Park [activation]", "IMG_4462", 1),
    ("night", "Outdoor & waterfront", "King Edward Park — &quot;Disney&quot; outside, all year", "IMG_4465", 1),

    # ---- Lighting, safety & atmosphere ----
    ("night", "Lighting & safety", "Lighting + the presence of people make a place feel safe", "IMG_4531", 3),
    ("night", "Lighting & safety", "Beautiful artistic lighting", "IMG_4539", 3),
    ("night", "Lighting & safety", "Vivid lighting show", "IMG_4529", 3),
    ("night", "Lighting & safety", "Unprogrammed busy spaces — lighting work", "IMG_4529", 3),
    ("night", "Lighting & safety", "SAFETY — &quot;Perception&quot;", "IMG_4530", 3),
    ("night", "Lighting & safety", "Safer well-lit areas for night runs, parks etc", "IMG_4532", 3),
    ("night", "Lighting & safety", "Well-lit areas with accessible parking", "IMG_4537", 3),
    ("night", "Lighting & safety", "Community parks with diffuse lighting connecting hotspots", "IMG_4531", 3),
    ("night", "Lighting & safety", "Coloured foot paths to connect the city", "IMG_4526", 3),
    ("night", "Lighting & safety", "People around — &quot;looked after&quot; space, knowing people", "IMG_4537", 3),

    # ---- Suburbs &amp; decentralised nightlife ----
    ("night", "Suburbs & decentralised", "Neighbourhood / suburb night life — enhance, rather than the focus of one precinct only", "IMG_4520", 3),
    ("night", "Suburbs & decentralised", "HUBS in SUBURBS (every certain months)", "IMG_4521", 3),
    ("night", "Suburbs & decentralised", "A village square in each neighbourhood", "IMG_4538", 3),
    ("night", "Suburbs & decentralised", "Western hub", "IMG_4541", 3),
    ("night", "Suburbs & decentralised", "Diversity of people", "IMG_4538", 3),
    ("night", "Suburbs & decentralised", "Having more community hotspots for people to stop in and connect", "IMG_4463", 1),

    # ---- Programming, rituals & formats ----
    ("night", "Programming & rituals", "Vendors coming to venues once a month for an event", "IMG_4527", 3),
    ("night", "Programming & rituals", "Eat Street markets (Fri + Sat)", "IMG_4526", 3),
    ("night", "Programming & rituals", "Night-time bakeries", "IMG_4520", 3),
    ("night", "Programming & rituals", "Night-time cafe crawls", "IMG_4520", 3),
    ("night", "Programming & rituals", "Phone-free events", "IMG_4526", 3),
    ("night", "Programming & rituals", "6-course dining in a fancy restaurant", "IMG_4526", 3),
    ("night", "Programming & rituals", "Immersive &amp; interactive experience", "IMG_4533", 3),
    ("night", "Programming & rituals", "Making sure the natural world is considered", "IMG_4533", 3),
    ("night", "Programming & rituals", "Small groups that try something new and others join", "IMG_4533", 3),
    ("night", "Programming & rituals", "Multi-use public space connected with venues — skate parks, parks, music, eating spaces", "IMG_4532", 3),
    ("night", "Programming & rituals", "Monthly open-street arts", "IMG_4523", 3),
    ("night", "Programming & rituals", "Free concerts", "IMG_4525", 3),
    ("night", "Programming & rituals", "Live sport — music space", "IMG_4520", 3),
    ("night", "Programming & rituals", "Social + cultural connection + experiences", "IMG_4545", 3),
    ("night", "Programming & rituals", "Speakers' Corner", "IMG_4460", 1),
    ("night", "Programming & rituals", "SPECIAL INTEREST GROUPS — outdoor moon expos", "IMG_4459", 1),
    ("night", "Programming & rituals", "MORE EVENTS → (Birdsmeadow?)", "IMG_4488", 2),

    # ---- Drinking &amp; non-drinking culture ----
    ("night", "Drinking culture", "Non-drinking culture", "IMG_4544", 3),
    ("night", "Drinking culture", "Pre-drinks at home — cheap entry — drink deals", "IMG_4538", 3),
    ("night", "Drinking culture", "More outdoor drinking spaces", "IMG_4521", 3),
    ("night", "Drinking culture", "Cafe &amp; bar (instead of pub) + more wineries [reading uncertain]", "IMG_4521", 3),
    ("night", "Drinking culture", "Safe communal areas with little pop-ups — gelato carts, wine bars, live music; like a piazza in Italy", "IMG_4536", 3),
    ("night", "Drinking culture", "Wall ball with lights + more courts", "IMG_4521", 3),

    # ---- Venues for age brackets ----
    ("night", "Age-bracket venues", "Venues for age brackets — 14–17, 18–25, 25+", "IMG_4532", 3),
    ("night", "Age-bracket venues", "Venues that are kid friendly", "IMG_4521", 3),
    ("night", "Age-bracket venues", "What should exist: late-night arcades, VR centres, games + entertainment alternatives to the harbour", "IMG_4521", 3),
    ("night", "Age-bracket venues", "Creative incentive — well-advertised, well-placed pop-up businesses", "IMG_4521", 3),

    # ---- Voices &amp; vision ----
    ("night", "Voices & vision", "More variety in night life", "IMG_4530", 3),
    ("night", "Voices & vision", "We're early birds — 6am hustle", "IMG_4530", 3),
    ("night", "Voices & vision", "Already busy", "IMG_4539", 3),
    ("night", "Voices & vision", "Coordination problem (thanks George) — but people's element seems to mediate first [reading uncertain]", "IMG_4533", 3),
    ("night", "Voices & vision", "@ Uni", "IMG_4530", 3),
    ("night", "Voices & vision", "We don't actually need to spend much. Newcastle — what we have, we just haven't activated yet — make it all accessible", "IMG_4460", 1),
    ("night", "Voices & vision", "Cut community members &amp; gather school children &amp; talk inside whilst drawn to school (not driving) [reading uncertain]", "IMG_4460", 1),
]
